import AppShell from '@/Components/layout/AppShell'
import { Head, Link, router } from '@inertiajs/react'

export default function InventoryReservationShow({ reservation }) {
    const active = reservation.status === 'ACTIVE'
    const action = (name) => router.post('/almacen/reservas/' + reservation.id + '/' + name, {}, { preserveScroll: true })

    return <AppShell title="Detalle de reserva"><Head title="Detalle de reserva" /><div className="mx-auto max-w-2xl space-y-6"><Link href="/almacen/reservas" className="text-sm font-semibold text-indigo-600 hover:underline dark:text-indigo-300">← Volver a reservas</Link><div className="rounded-2xl border border-slate-200 bg-white p-6 dark:border-neutral-800 dark:bg-neutral-900"><h1 className="text-2xl font-bold dark:text-white">{reservation.product?.name}</h1><p className="mt-1 font-mono text-sm text-slate-500">{reservation.product?.sku}</p><dl className="mt-5 grid gap-4 sm:grid-cols-2"><div><dt className="text-xs uppercase text-slate-500">Ubicación</dt><dd className="mt-1 dark:text-white">{reservation.location?.code || 'Global'}</dd></div><div><dt className="text-xs uppercase text-slate-500">Cantidad</dt><dd className="mt-1 font-bold dark:text-white">{reservation.quantity}</dd></div><div><dt className="text-xs uppercase text-slate-500">Estado</dt><dd className="mt-1 dark:text-white">{reservation.status}</dd></div><div><dt className="text-xs uppercase text-slate-500">Fuente</dt><dd className="mt-1 dark:text-white">{reservation.source_type || '—'} / {reservation.source_id || '—'}</dd></div><div><dt className="text-xs uppercase text-slate-500">Referencia</dt><dd className="mt-1 dark:text-white">{reservation.reference || '—'}</dd></div><div><dt className="text-xs uppercase text-slate-500">Expiración</dt><dd className="mt-1 dark:text-white">{reservation.expires_at || '—'}</dd></div><div><dt className="text-xs uppercase text-slate-500">Creada por</dt><dd className="mt-1 dark:text-white">{reservation.created_by?.name || '—'}</dd></div><div><dt className="text-xs uppercase text-slate-500">Creada</dt><dd className="mt-1 dark:text-white">{reservation.created_at}</dd></div></dl>{active && <div className="mt-6 flex flex-wrap gap-3"><button type="button" onClick={() => action('liberar')} className="rounded-xl bg-amber-600 px-4 py-2.5 font-semibold text-white">Liberar</button><button type="button" onClick={() => action('cancelar')} className="rounded-xl bg-rose-600 px-4 py-2.5 font-semibold text-white">Cancelar</button><button type="button" onClick={() => action('cumplir')} className="rounded-xl bg-emerald-600 px-4 py-2.5 font-semibold text-white">Cumplir</button></div>}</div></div></AppShell>
}
