import AppShell from '@/Components/layout/AppShell'
import { Head, Link, useForm } from '@inertiajs/react'

export default function InventoryKitForm({ kit, products = [] }) {
    const { data, setData, put, processing, errors } = useForm({ components: (kit.kit_components || []).map((row) => ({ component_product_id: row.component_product_id, quantity: row.quantity })) })
    const submit = (event) => { event.preventDefault(); put(`/almacen/kits/${kit.id}/componentes`) }
    const updateRow = (index, changes) => setData('components', data.components.map((item, i) => i === index ? { ...item, ...changes } : item))
    const add = () => setData('components', [...data.components, { component_product_id: products[0]?.id || '', quantity: 1 }])
    return <AppShell title="Componentes del kit"><Head title={`Componentes · ${kit.name}`} /><div className="mx-auto max-w-3xl space-y-6"><Link href={`/almacen/kits/${kit.id}`} className="text-sm font-semibold text-indigo-600">← Volver al kit</Link><h1 className="text-3xl font-bold">Componentes de {kit.name}</h1><form onSubmit={submit} className="space-y-5 rounded-2xl border border-slate-200 bg-white p-6 dark:border-neutral-800 dark:bg-neutral-900">{data.components.map((row, index) => <div key={index} className="flex gap-3"><select value={row.component_product_id} onChange={(event) => updateRow(index, { component_product_id: event.target.value })} className="flex-1 rounded-xl border px-3 py-2 dark:border-neutral-700 dark:bg-neutral-950">{products.map((product) => <option key={product.id} value={product.id}>{product.name} · {product.sku}</option>)}</select><input type="number" min="1" value={row.quantity} onChange={(event) => updateRow(index, { quantity: event.target.value })} className="w-24 rounded-xl border px-3 py-2 dark:border-neutral-700 dark:bg-neutral-950" /><button type="button" onClick={() => setData('components', data.components.filter((_, i) => i !== index))} className="text-rose-600">Quitar</button></div>)}{errors.components && <p className="text-sm text-rose-600">{errors.components}</p>}<div className="flex justify-between"><button type="button" onClick={add} className="rounded-xl border px-4 py-2 font-semibold">Agregar componente</button><button disabled={processing} className="rounded-xl bg-indigo-600 px-5 py-2 font-semibold text-white">Guardar</button></div></form></div></AppShell>
}
