import AppShell from '@/Components/layout/AppShell'
import { accountName, accountSecondary, actionName, availableAction, claimStage, claimStatus, claimType, expectedResolution, historyAction, listData, playerRole, resolutionName } from '@/lib/meliClaimsPresentation'
import { Head, Link } from '@inertiajs/react'

const date = value => value ? new Date(value).toLocaleString('es-MX') : '—'
const money = value => value === null || value === undefined ? '—' : new Intl.NumberFormat('es-MX', { style: 'currency', currency: 'MXN' }).format(value)

export default function Show({ claim }) {
    return <AppShell title="Reclamos"><Head title={`Reclamo ${claim.claim_id}`} /><div className="mx-auto max-w-5xl space-y-5 p-4 sm:p-6"><Link href="/meli-claims" className="text-sm font-bold text-indigo-600">← Volver a reclamos</Link><header><h1 className="text-2xl font-black">Reclamo {claim.claim_id}</h1><p className="text-slate-500">Solo lectura. Ninguna acción se ejecuta en Mercado Libre.</p></header>
        <section className="grid gap-4 md:grid-cols-2">
            <Card title="Resumen"><Rows rows={[["Cuenta", accountName(claim.account)], ['ID de cuenta', accountSecondary(claim.account)], ['Pedido', claim.order_id], ['Monto relacionado', money(claim.order_amount)], ['Estado', claimStatus(claim.status)], ['Etapa', claimStage(claim.stage)], ['Tipo', claimType(claim.type)], ['Creado', date(claim.date_created)], ['Actualizado', date(claim.last_updated)]]} /></Card>
            <Card title="Problema"><Rows rows={[["Motivo", claim.reason], ['Código interno', claim.reason_id], ['Título', claim.detail_title], ['Descripción', claim.detail_description], ['Problema', claim.problem]]} /></Card>
            <Card title="Reputación"><Rows rows={[["Resultado", claim.affects_reputation === true ? 'Afecta reputación' : claim.affects_reputation === false ? 'No afecta reputación' : 'Sin información'], ['Tiene incentivo', claim.reputation_has_incentive === true ? 'Sí' : claim.reputation_has_incentive === false ? 'No' : 'Sin información'], ['Plazo', date(claim.reputation_due_date)]]} /></Card>
            <Card title="Resolución disponible (informativa)"><ResolutionList value={claim.expected_resolutions} /><h3 className="mt-5 font-bold">Acciones disponibles según Mercado Libre</h3><ActionList value={claim.available_actions} /></Card>
        </section>
        <Card title="Productos relacionados"><ProductList products={claim.products} /></Card>
        <Card title="Historial de estados"><Timeline values={listData(claim.status_history)} kind="status" /></Card>
        <Card title="Historial de acciones"><Timeline values={listData(claim.actions_history)} kind="action" /></Card>
    </div></AppShell>
}

function Card({ title, children }) { return <section className="rounded-xl border bg-white p-5 dark:border-neutral-800 dark:bg-neutral-900"><h2 className="mb-4 text-lg font-black">{title}</h2>{children}</section> }
function Rows({ rows }) { return <dl className="space-y-2">{rows.map(([key, value]) => <div key={key}><dt className="text-xs font-bold uppercase text-slate-500">{key}</dt><dd className="whitespace-pre-wrap">{value ?? '—'}</dd></div>)}</dl> }
function ProductList({ products }) { return products.length ? <div className="grid gap-3 md:grid-cols-2">{products.map((product, index) => <article key={`${product.mlm}-${index}`} className="flex gap-4 rounded-lg border p-3">{product.thumbnail && <img src={product.thumbnail} alt="" className="h-20 w-20 rounded object-cover" />}<div><p className="font-bold">{product.title || 'Producto sin título'}</p><p className="text-sm text-slate-500">{product.mlm || 'MLM no disponible'} · SKU {product.sku || '—'}</p><p className="text-sm">Cantidad: {product.quantity} · Precio: {money(product.unit_price)} · Importe: {money(product.amount)}</p></div></article>)}</div> : <p className="text-slate-500">No hay productos locales relacionados.</p> }
function ActionList({ value }) { const actions = listData(value); return actions.length ? <ul className="mt-2 space-y-2">{actions.map((item, index) => <li key={index} className="rounded-lg bg-slate-50 p-3 dark:bg-neutral-800"><p className="font-bold">{availableAction(actionName(item))}</p>{typeof item === 'object' && item.player_role && <p className="text-sm text-slate-500">Actor: {playerRole(item.player_role)}</p>}</li>)}</ul> : <p className="mt-2 text-slate-500">Sin acciones informadas.</p> }
function ResolutionList({ value }) { const resolutions = listData(value); return resolutions.length ? <ul className="space-y-2">{resolutions.map((item, index) => <li key={index} className="rounded-lg bg-slate-50 p-3 dark:bg-neutral-800"><p className="font-bold">{expectedResolution(resolutionName(item))}</p>{typeof item === 'object' && <p className="text-sm text-slate-500">{item.status && <>Estado: {claimStatus(item.status)}</>}{(item.player_role || item.role) && <> · Actor: {playerRole(item.player_role || item.role)}</>}</p>}</li>)}</ul> : <p className="text-slate-500">Mercado Libre no informa una resolución esperada actualmente.</p> }
function Timeline({ values, kind }) { return values.length ? <ol className="space-y-3 border-l pl-4">{values.map((item, index) => { const rawName = kind === 'action' ? actionName(item) : item.status || item.stage || item.type; const title = kind === 'action' ? historyAction(rawName) : (item.status ? claimStatus(item.status) : claimStage(rawName)); const actor = item.player_role || item.change_by || item.role; return <li key={index}><p className="font-bold">{title}</p>{actor && <p className="text-sm">Actor: {playerRole(actor)}</p>}<p className="text-sm text-slate-500">{date(item.date || item.date_created || item.created_at)}</p>{(item.description || item.reason) && <p className="text-sm">{item.description || item.reason}</p>}</li> })}</ol> : <p className="text-slate-500">Sin historial disponible.</p> }
