import AppShell from '@/Components/layout/AppShell'
import { formatDateTime, movementTypeLabel } from '@/lib/inventoryPresentation'
import { Head, Link } from '@inertiajs/react'

function money(value) {
    if (value === null || value === undefined || value === '') return '—'
    return new Intl.NumberFormat('es-MX', { style: 'currency', currency: 'MXN', minimumFractionDigits: 2 }).format(Number(value))
}

export default function InventoryProductShow({ product, physicalStock = 0, reservedStock = 0, availableStock = 0, stockByLocation = [], movements = [], reservations = [], kitComponents = [], channelLinks = [] }) {
    const isKit = product.product_type === 'KIT'

    return (
        <AppShell title="Producto de almacén">
            <Head title={product.name} />
            <div className="mx-auto max-w-3xl space-y-6">
                <div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><Link href="/almacen/productos" className="text-sm font-semibold text-indigo-600 hover:underline dark:text-indigo-300">← Volver al catálogo</Link><h1 className="mt-3 text-3xl font-bold text-slate-900 dark:text-white">{product.name}</h1></div><Link href={`/almacen/productos/${product.id}/editar`} className="rounded-xl bg-indigo-600 px-4 py-2.5 text-center font-semibold text-white">Editar</Link></div>
                <div className="grid gap-4 rounded-2xl border border-slate-200 bg-white p-6 sm:grid-cols-2 dark:border-neutral-800 dark:bg-neutral-900">{[['SKU', product.sku], ['Tipo', product.product_type || 'SIMPLE'], ['Código de barras', product.barcode || '—'], ['Segundo código de barras', product.barcode_secondary || '—'], ['Ubicación principal (Picking)', isKit ? '📦 Derivada de componentes' : (product.primary_location?.code || 'Sin ubicación')], ['Ubicación secundaria (Reserva)', isKit ? '📦 Derivada de componentes' : (product.secondary_location?.code || 'Sin reserva')], ['Notas de reserva', isKit ? 'Ver componentes abajo' : (product.reserve_notes || '—')], [isKit ? 'Stock derivado / físico posible' : 'Stock físico', Number(physicalStock || 0)], ['Reservado', Number(reservedStock || 0)], ['Disponible', Number(availableStock || 0)], ['Costo', money(product.cost)], ['Precio Mercado Libre', money(product.price_mercado_libre)], ['Precio Amazon', money(product.price_amazon)], ['Precio estilista / Shopify', money(product.price_stylist)], ['Precio público', money(product.price_public)], ['Estado', product.is_active ? 'Activo' : 'Inactivo']].map(([label, value]) => <div key={label}><dt className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</dt><dd className="mt-1 text-slate-900 dark:text-white">{value}</dd></div>)}<div className="sm:col-span-2"><dt className="text-xs font-semibold uppercase tracking-wide text-slate-500">Descripción</dt><dd className="mt-1 whitespace-pre-wrap text-slate-700 dark:text-slate-300">{product.description || '—'}</dd></div></div>
                {isKit && <section className="rounded-2xl border border-slate-200 bg-white dark:border-neutral-800 dark:bg-neutral-900"><div className="flex items-center justify-between border-b border-slate-200 px-5 py-4 font-bold dark:border-neutral-800"><span>Componentes del kit y ubicaciones</span><Link href={`/almacen/kits/${product.id}/editar-componentes`} className="text-sm font-semibold text-indigo-600">Configurar</Link></div><div className="divide-y divide-slate-100 dark:divide-neutral-800">{kitComponents.length === 0 ? <p className="px-5 py-5 text-sm text-amber-700">Kit sin componentes configurados.</p> : kitComponents.map((row) => { const comp = row.component || {}; const pickCode = row.primary_location_code || comp.primary_location?.code || comp.primaryLocation?.code; const pickAisle = row.primary_location_aisle || comp.primary_location?.amazon_aisle || comp.primaryLocation?.amazon_aisle; const resCode = row.secondary_location_code || comp.secondary_location?.code || comp.secondaryLocation?.code; const resAisle = row.secondary_location_aisle || comp.secondary_location?.amazon_aisle || comp.secondaryLocation?.amazon_aisle; const notes = row.reserve_notes || comp.reserve_notes; return <div key={row.id || comp.id} className="p-4 space-y-1.5 text-sm"><div className="flex flex-wrap items-center justify-between gap-2"><div><span className="font-semibold text-slate-900 dark:text-white">{comp.name}</span> <span className="font-mono text-xs text-slate-500">({comp.sku})</span></div><div className="flex items-center gap-3 text-xs"><span>Requiere: <strong>{row.quantity} pza</strong></span><span>Físico: <strong>{row.physical_stock}</strong></span><strong className="text-emerald-700 dark:text-emerald-400">Disponible: {row.available_stock}</strong></div></div><div className="flex flex-wrap items-center gap-2 text-xs"><span className={`inline-flex items-center rounded-md px-2 py-0.5 font-bold ${pickCode ? 'bg-emerald-100 text-emerald-800 dark:bg-emerald-950/60 dark:text-emerald-300' : 'bg-slate-100 text-slate-500'}`}>📍 Picking: {pickCode || 'Sin ubicación'}{pickAisle ? ` (P. ${pickAisle})` : ''}</span>{resCode && <span className="inline-flex items-center rounded-md bg-amber-100 px-2 py-0.5 font-bold text-amber-800 dark:bg-amber-950/60 dark:text-amber-300">📦 Reserva: {resCode}{resAisle ? ` (P. ${resAisle})` : ''}</span>}{notes && <span className="text-slate-500 italic">({notes})</span>}</div></div> })}</div></section>}
                <section className="rounded-2xl border border-slate-200 bg-white dark:border-neutral-800 dark:bg-neutral-900"><div className="flex items-center justify-between border-b border-slate-200 px-5 py-4 font-bold dark:border-neutral-800"><span>Enlaces de canales</span><Link href="/almacen/canales" className="text-sm font-semibold text-indigo-600">Ver todos</Link></div><div className="divide-y divide-slate-100 dark:divide-neutral-800">{channelLinks.length === 0 ? <p className="px-5 py-5 text-sm text-slate-500">Sin enlaces configurados.</p> : channelLinks.map((link) => <div key={link.id} className="flex flex-wrap items-center justify-between gap-2 px-5 py-3 text-sm"><span className="font-semibold">{link.channel}</span><span className="font-mono">{link.external_listing_id || link.external_product_id || link.external_variant_id || '—'}</span><span>{link.is_active ? 'Activo' : 'Inactivo'}</span></div>)}</div></section>
                <section className="rounded-2xl border border-slate-200 bg-white dark:border-neutral-800 dark:bg-neutral-900"><div className="border-b border-slate-200 px-5 py-4 font-bold dark:border-neutral-800">Stock por ubicación</div><div className="divide-y divide-slate-100 dark:divide-neutral-800">{stockByLocation.length === 0 ? <p className="px-5 py-5 text-sm text-slate-500">Sin movimientos ni reservas por ubicación.</p> : stockByLocation.map((row) => <div key={row.inventory_location_id} className="grid grid-cols-4 gap-2 px-5 py-3 text-sm"><span>{row.location?.code || 'Sin ubicación'}</span><span>Físico: {row.physical_stock}</span><span>Reservado: {row.reserved_stock}</span><strong>Disponible: {row.available_stock}</strong></div>)}</div></section>
                <section className="rounded-2xl border border-slate-200 bg-white dark:border-neutral-800 dark:bg-neutral-900"><div className="border-b border-slate-200 px-5 py-4 font-bold dark:border-neutral-800">Reservas activas recientes</div><div className="divide-y divide-slate-100 dark:divide-neutral-800">{reservations.length === 0 ? <p className="px-5 py-5 text-sm text-slate-500">Sin reservas activas.</p> : reservations.map((reservation) => <div key={reservation.id} className="flex flex-wrap items-center justify-between gap-2 px-5 py-3 text-sm"><span>{reservation.location?.code || 'Global'} · {reservation.reference || 'Sin referencia'} <span className="text-slate-500">· {formatDateTime(reservation.created_at)}</span></span><strong>{reservation.quantity}</strong></div>)}</div></section>
                <section className="rounded-2xl border border-slate-200 bg-white dark:border-neutral-800 dark:bg-neutral-900"><div className="border-b border-slate-200 px-5 py-4 font-bold dark:border-neutral-800">Últimos movimientos</div><div className="divide-y divide-slate-100 dark:divide-neutral-800">{movements.length === 0 ? <p className="px-5 py-5 text-sm text-slate-500">Sin movimientos registrados.</p> : movements.map((movement) => <div key={movement.id} className="flex flex-wrap items-center justify-between gap-2 px-5 py-3 text-sm"><span>{formatDateTime(movement.occurred_at)} · {movementTypeLabel(movement.type)} · {movement.location?.code}</span><strong className={Number(movement.quantity) >= 0 ? 'text-emerald-700' : 'text-rose-700'}>{Number(movement.quantity) >= 0 ? '+' : ''}{movement.quantity}</strong></div>)}</div></section>
            </div>
        </AppShell>
    )
}
