import AppShell from '@/Components/layout/AppShell'
import { Head, Link, router, useForm } from '@inertiajs/react'

function Field({ label, value }) {
    return <div><dt className="text-xs font-semibold uppercase text-slate-500">{label}</dt><dd className="mt-1 whitespace-pre-wrap text-sm text-slate-800 dark:text-slate-200">{value ?? '—'}</dd></div>
}

export default function CategoriaMeliDetalle({ part, categories = {}, meli = {} }) {
    const manual = useForm({ category_id: '', review_notes: '' })
    const readiness = part.meli_readiness
    const disabledReason = !meli.enabled ? 'La integración está deshabilitada.' : (meli.daily_remaining < 1 ? 'Se alcanzó el límite diario.' : null)
    const search = () => {
        if (window.confirm('¿Buscar candidatos oficiales? La acción solo encola metadatos y no publica.')) router.post(`/autopartes/mercado-libre/categorias/${part.id}/buscar`)
    }
    const reject = (candidate) => {
        const notes = window.prompt('Motivo obligatorio del rechazo:')
        if (notes) router.post(`/autopartes/mercado-libre/categorias/candidatos/${candidate.id}/rechazar`, { review_notes: notes })
    }
    const approve = (candidate) => {
        if (window.confirm(`¿Aprobar ${candidate.category_id}? Se sincronizarán atributos, pero no se publicará.`)) router.post(`/autopartes/mercado-libre/categorias/candidatos/${candidate.id}/aprobar`)
    }

    return (
        <AppShell title="Mapeo ML de autoparte">
            <Head title={`Categoría ML ${part.item_number ?? part.id}`} />
            <div className="space-y-6">
                <div className="flex flex-col justify-between gap-3 md:flex-row md:items-center"><div><h1 className="text-2xl font-bold text-slate-900 dark:text-white">{part.item_number ?? `Autoparte #${part.id}`}</h1><p className="text-sm text-slate-500">{part.manufacturer_part_number ?? 'Sin MFG Part #'} · {part.category ?? '—'} / {part.subcategory ?? '—'}</p></div><div className="flex gap-2"><button type="button" onClick={search} disabled={Boolean(disabledReason)} title={disabledReason ?? ''} className="rounded-xl bg-sky-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">Buscar candidatos</button><Link href="/autopartes/mercado-libre/categorias" className="rounded-xl border border-slate-200 px-4 py-2 text-sm font-semibold dark:border-neutral-700">Volver</Link></div></div>

                <section className="rounded-2xl border border-slate-200 bg-white p-5 dark:border-neutral-800 dark:bg-neutral-900"><h2 className="text-lg font-semibold">Datos de origen</h2><dl className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Field label="Descripción" value={part.description_original} /><Field label="Proveedor" value={part.vendor} /><Field label="Modelo prevalente" value={part.prevalent_model} /><Field label="Compatibilidad" value={part.applicable_models_text} /><Field label="Años" value={[part.min_model_year, part.max_model_year].filter((v) => v !== null).join('–') || null} /><Field label="Dimensiones cm" value={[part.length_cm, part.width_cm, part.height_cm].filter((v) => v !== null).join(' × ') || null} /><Field label="Peso kg" value={part.weight_kg} /><Field label="Lifecycle" value={part.lifecycle} /></dl></section>

                <section className="rounded-2xl border border-sky-200 bg-sky-50 p-5 dark:border-sky-500/20 dark:bg-sky-500/5"><h2 className="text-lg font-semibold">Estado de preparación: {readiness?.status ?? 'unmapped'}</h2><div className="mt-4 grid gap-4 lg:grid-cols-3"><div><h3 className="text-sm font-semibold">Atributos propuestos</h3><pre className="mt-2 max-h-80 overflow-auto whitespace-pre-wrap rounded-xl bg-white p-3 text-xs dark:bg-neutral-950">{JSON.stringify(readiness?.proposed_attributes ?? [], null, 2)}</pre></div><div><h3 className="text-sm font-semibold">Obligatorios faltantes</h3><pre className="mt-2 max-h-80 overflow-auto whitespace-pre-wrap rounded-xl bg-white p-3 text-xs dark:bg-neutral-950">{JSON.stringify(readiness?.missing_required_attributes ?? [], null, 2)}</pre></div><div><h3 className="text-sm font-semibold">Compatibilidad y advertencias</h3><pre className="mt-2 max-h-80 overflow-auto whitespace-pre-wrap rounded-xl bg-white p-3 text-xs dark:bg-neutral-950">{JSON.stringify({ compatibility: readiness?.compatibility_requirements, warnings: readiness?.warnings, conditional: readiness?.missing_conditional_attributes }, null, 2)}</pre></div></div><div className="mt-4 flex gap-2"><button type="button" onClick={() => router.post(`/autopartes/mercado-libre/categorias/${part.id}/recalcular`)} className="rounded-xl border border-sky-300 px-4 py-2 text-sm font-semibold">Recalcular</button><button type="button" disabled={readiness?.status !== 'ready_for_review'} onClick={() => router.post(`/autopartes/mercado-libre/categorias/${part.id}/confirmar`)} className="rounded-xl bg-emerald-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-40">Confirmar revisión final</button></div></section>

                <section className="rounded-2xl border border-slate-200 bg-white p-5 dark:border-neutral-800 dark:bg-neutral-900"><h2 className="text-lg font-semibold">Candidatos e historial</h2><div className="mt-4 space-y-4">{(part.meli_category_candidates ?? []).map((candidate) => {
                    const category = categories[candidate.category_id]
                    const path = category?.path_from_root?.map((node) => node.name).join(' › ')
                    return <article key={candidate.id} className="rounded-xl border border-slate-200 p-4 dark:border-neutral-700"><div className="flex flex-col justify-between gap-3 md:flex-row"><div><h3 className="font-semibold">{candidate.category_name} <span className="text-slate-500">({candidate.category_id})</span></h3><p className="text-xs text-slate-500">{path ?? 'Path pendiente'} · fuente {candidate.source} · posición {candidate.position ?? '—'} · score {candidate.score ?? 'no proporcionado'}</p><p className="mt-2 text-sm">Estado: <strong>{candidate.status}</strong>{candidate.review_notes ? ` · ${candidate.review_notes}` : ''}</p></div>{candidate.status === 'pending' && <div className="flex gap-2"><button type="button" disabled={Boolean(disabledReason)} onClick={() => approve(candidate)} className="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-semibold text-white disabled:opacity-40">Aprobar</button><button type="button" onClick={() => reject(candidate)} className="rounded-lg bg-rose-600 px-3 py-2 text-xs font-semibold text-white">Rechazar</button><button type="button" disabled={Boolean(disabledReason)} onClick={() => router.post(`/autopartes/mercado-libre/categorias/candidatos/${candidate.id}/actualizar`, { refresh_metadata: true })} className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold disabled:opacity-40">Actualizar metadatos</button></div>}</div><details className="mt-3"><summary className="cursor-pointer text-xs font-semibold text-slate-500">Sección técnica: evidencia y respuesta cruda</summary><pre className="mt-2 max-h-96 overflow-auto whitespace-pre-wrap rounded-xl bg-slate-50 p-3 text-xs dark:bg-neutral-950">{JSON.stringify({ evidence: candidate.evidence, raw_payload: candidate.raw_payload, category: category?.raw_payload, attributes: category?.attribute_requirements }, null, 2)}</pre></details></article>
                })}{(part.meli_category_candidates ?? []).length === 0 && <p className="text-sm text-slate-500">No hay candidatos todavía.</p>}</div></section>

                <form onSubmit={(event) => { event.preventDefault(); manual.post(`/autopartes/mercado-libre/categorias/${part.id}/manual`, { preserveScroll: true }) }} className="rounded-2xl border border-slate-200 bg-white p-5 dark:border-neutral-800 dark:bg-neutral-900"><h2 className="text-lg font-semibold">Capturar category_id manual</h2><p className="mt-1 text-xs text-slate-500">Se validará contra la API oficial y quedará pendiente; no se aprobará automáticamente.</p><div className="mt-4 grid gap-3 md:grid-cols-3"><input value={manual.data.category_id} onChange={(event) => manual.setData('category_id', event.target.value.toUpperCase())} placeholder="MLM123456" className="rounded-xl border border-slate-200 px-3 py-2 text-sm dark:border-neutral-700 dark:bg-neutral-950" /><input value={manual.data.review_notes} onChange={(event) => manual.setData('review_notes', event.target.value)} placeholder="Nota opcional" className="rounded-xl border border-slate-200 px-3 py-2 text-sm dark:border-neutral-700 dark:bg-neutral-950" /><button disabled={manual.processing || Boolean(disabledReason)} className="rounded-xl bg-slate-900 px-4 py-2 text-sm font-semibold text-white disabled:opacity-40 dark:bg-white dark:text-slate-900">Validar y guardar candidato</button></div>{manual.errors.category_id && <p className="mt-2 text-sm text-rose-600">{manual.errors.category_id}</p>}{manual.errors.meli && <p className="mt-2 text-sm text-rose-600">{manual.errors.meli}</p>}</form>
            </div>
        </AppShell>
    )
}
