import AppShell from '@/Components/layout/AppShell'
import { Head, Link, router, useForm } from '@inertiajs/react'

export default function MediosDetalle({ part, settings = {} }) {
    const form = useForm({ image: null, provenance_type: 'user_upload', provenance_reference: '', notes: '' })
    const action = (id, name, data = {}) => router.post(`/autopartes/medios/archivos/${id}/${name}`, data, { preserveScroll: true })
    const move = (id, delta) => { const ids = part.media.map(x => x.id); const from = ids.indexOf(id); const to = from + delta; if (to < 0 || to >= ids.length) return; [ids[from], ids[to]] = [ids[to], ids[from]]; router.put(`/autopartes/medios/${part.id}/orden`, { media_ids: ids }, { preserveScroll: true }) }
    return <AppShell title="Medios de Autoparte"><Head title="Medios de Autoparte" /><div className="space-y-5">
        <div><Link href="/autopartes/medios" className="text-sm text-sky-700">← Medios</Link><h1 className="text-2xl font-bold">{part.item_number ?? `Autoparte #${part.id}`}</h1><p className="text-sm text-slate-500">{part.description_original}</p></div>
        <div className="rounded-xl border border-amber-300 bg-amber-50 p-4 font-semibold text-amber-950">La imagen debe ser propia o estar autorizada.</div>
        <form onSubmit={e => { e.preventDefault(); form.post(`/autopartes/medios/${part.id}`, { forceFormData: true }) }} className="grid gap-3 rounded-xl border p-4 md:grid-cols-2">
            <input type="file" accept="image/jpeg,image/png,image/webp" onChange={e => form.setData('image', e.target.files[0])}/><select value={form.data.provenance_type} onChange={e => form.setData('provenance_type', e.target.value)} className="rounded-lg border p-2">{(settings.provenance_types ?? []).map(x => <option key={x}>{x}</option>)}</select>
            <input value={form.data.provenance_reference} onChange={e => form.setData('provenance_reference', e.target.value)} className="rounded-lg border p-2" placeholder="Referencia de procedencia"/><input value={form.data.notes} onChange={e => form.setData('notes', e.target.value)} className="rounded-lg border p-2" placeholder="Notas"/><button disabled={!settings.enabled || form.processing} className="rounded-lg bg-slate-900 px-4 py-2 text-white disabled:opacity-40">Cargar respaldo</button>
        </form>
        <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{part.media.map(media => <article key={media.id} className="rounded-xl border p-3"><img src={`/autopartes/medios/archivos/${media.id}/preview`} className="h-52 w-full rounded-lg object-contain"/><div className="mt-2 flex justify-between"><strong>{media.status}{media.is_primary ? ' · principal' : ''}</strong><span>#{media.position}</span></div><p className="text-xs text-slate-500">{media.provenance_type} · {media.original_name}</p><p className="break-all text-xs text-slate-400">SHA-256 {media.sha256}</p><div className="mt-3 flex flex-wrap gap-2">{media.status === 'pending' && <button onClick={() => action(media.id, 'aprobar')} className="rounded border px-2 py-1">Aprobar</button>}{media.status !== 'archived' && <button onClick={() => action(media.id, 'rechazar', { notes: window.prompt('Nota de rechazo') ?? '' })} className="rounded border px-2 py-1">Rechazar</button>}{media.status === 'approved' && !media.is_primary && <button onClick={() => action(media.id, 'principal')} className="rounded border px-2 py-1">Principal</button>}{media.status !== 'archived' && <button onClick={() => action(media.id, 'archivar')} className="rounded border px-2 py-1">Archivar</button>}<button onClick={() => move(media.id, -1)} className="rounded border px-2 py-1">↑</button><button onClick={() => move(media.id, 1)} className="rounded border px-2 py-1">↓</button></div><details className="mt-3 text-xs"><summary>Historial y metadata</summary><pre className="overflow-auto">{JSON.stringify({ metadata: media.metadata, events: media.events }, null, 2)}</pre></details></article>)}</div>
    </div></AppShell>
}
