import AppShell from '@/Components/layout/AppShell'
import { Head, Link, useForm } from '@inertiajs/react'

export default function Precios({ rules, settings = {} }) {
    const form = useForm({ name: '', scope_type: 'global', scope_value: '', source_currency: 'USD', target_currency: 'MXN', usd_mxn_rate: '', markup_percent: 0, meli_fee_percent: 0, fixed_cost_mxn: 0, rounding_mode: 'nearest', rounding_increment: 1, minimum_price_mxn: '', maximum_price_mxn: '', effective_from: new Date().toISOString().slice(0, 16), effective_until: '', notes: '' })
    return <AppShell title="Precios de Autopartes"><Head title="Precios de Autopartes" /><div className="space-y-5">
        <div className="flex justify-between"><div><h1 className="text-2xl font-bold">Reglas de precio MXN</h1><p className="text-sm text-slate-500">Versionadas, aprobadas y auditables.</p></div><Link href="/autopartes/medios" className="rounded-lg border px-3 py-2">Medios</Link></div>
        <div className="space-y-1 rounded-xl border border-amber-300 bg-amber-50 p-4 font-semibold text-amber-950"><p>Este precio es un cálculo interno y no modifica Mercado Libre.</p><p>Activar una regla no publica ni cambia precios externos.</p></div>
        <form onSubmit={e => { e.preventDefault(); form.post('/autopartes/precios/reglas') }} className="grid gap-2 rounded-xl border p-4 md:grid-cols-4">
            {['name','scope_value','usd_mxn_rate','markup_percent','meli_fee_percent','fixed_cost_mxn','rounding_increment','minimum_price_mxn','maximum_price_mxn','effective_from','effective_until','notes'].map(key => <input key={key} type={key.startsWith('effective') ? 'datetime-local' : 'text'} value={form.data[key]} onChange={e => form.setData(key, e.target.value)} className="rounded-lg border p-2" placeholder={key}/>)}
            <select value={form.data.scope_type} onChange={e => form.setData('scope_type', e.target.value)} className="rounded-lg border p-2">{(settings.scopes ?? []).map(x => <option key={x}>{x}</option>)}</select><select value={form.data.rounding_mode} onChange={e => form.setData('rounding_mode', e.target.value)} className="rounded-lg border p-2">{(settings.rounding_modes ?? []).map(x => <option key={x}>{x}</option>)}</select><button disabled={!settings.enabled} className="rounded-lg bg-slate-900 p-2 text-white disabled:opacity-40">Crear borrador</button>
        </form>
        <div className="overflow-x-auto rounded-xl border"><table className="min-w-full text-sm"><thead><tr className="border-b text-left"><th className="p-3">Regla</th><th>Scope</th><th>Versión</th><th>Estado</th><th>Vigencia</th></tr></thead><tbody>{rules.data.map(rule => <tr key={rule.id} className="border-b"><td className="p-3"><Link href={`/autopartes/precios/reglas/${rule.id}`} className="font-semibold text-sky-700">{rule.name}</Link></td><td>{rule.scope_type}: {rule.scope_value ?? 'global'}</td><td>{rule.version}</td><td>{rule.status}</td><td>{rule.effective_from} — {rule.effective_until ?? 'sin fin'}</td></tr>)}</tbody></table></div>
    </div></AppShell>
}
