import AppShell from '@/Components/layout/AppShell'
import { Head, Link, router } from '@inertiajs/react'
import { useState } from 'react'

const post = (id, action, data = {}) => router.post(`/autopartes/mercado-libre/publicaciones/${id}/${action}`, data)

export default function PublicacionMeliDetalle({ publication: p, publisher = {} }) {
    const item = p.local_payload?.item_payload ?? {}
    const [approval, setApproval] = useState({note:'', confirm_account_id:'', confirm_title:'', confirm_price:'', confirm_stock:'', confirm_category_id:'', confirm_fingerprint_suffix:''})
    const set = (key) => (event) => setApproval({...approval,[key]:event.target.value})
    const approve = (event) => { event.preventDefault(); post(p.id, 'aprobar', approval) }
    const noteAction = (action) => { const note=window.prompt('Nota obligatoria:'); if(note) post(p.id, action, {note}) }
    const enqueue = () => { if(window.confirm('Esta acción puede crear una publicación real en Mercado Libre. ¿Confirmas cuenta, precio, stock y categoría?')) post(p.id,'encolar',{confirm_live_publication:true}) }
    const reconcile = () => { const resolution=window.prompt('Resolución exacta: item_found o not_created'); if(!resolution)return; const meli_item_id=resolution==='item_found'?window.prompt('Item ID MLM confirmado:'):null; const note=window.prompt('Nota de reconciliación:'); if(note)post(p.id,'reconciliar',{resolution,meli_item_id,note}) }
    return <AppShell title={`Publicación ML #${p.id}`}><Head title={`Publicación ML #${p.id}`}/><div className="space-y-6">
        <div className="flex justify-between gap-3"><div><h1 className="text-2xl font-bold">Publicación controlada #{p.id}</h1><p className="text-sm text-slate-500">Estado: <strong>{p.status}</strong> · borrador #{p.automotive_part_meli_draft_id} · cuenta {p.account?.nickname ?? p.seller_id}</p></div><Link href="/autopartes/mercado-libre/publicaciones" className="rounded-xl border px-4 py-2 text-sm">Volver</Link></div>
        <div className="rounded-2xl border border-rose-300 bg-rose-50 p-4 dark:bg-rose-500/10"><p className="font-bold">Esta acción puede crear una publicación real en Mercado Libre</p><p className="text-sm">La validación remota no publica. Después de crear el artículo no se repetirá automáticamente el POST. Confirma cuenta, precio, stock y categoría.</p></div>
        <section className="grid gap-4 rounded-2xl border p-5 md:grid-cols-2"><div className="space-y-1 text-sm"><h2 className="text-lg font-semibold">Resumen auditable</h2><p><b>Fingerprint:</b> {p.request_fingerprint}</p><p><b>Título:</b> {item.title}</p><p><b>Precio:</b> {item.price} {item.currency_id}</p><p><b>Stock:</b> {item.available_quantity}</p><p><b>Categoría:</b> {item.category_id}</p><p><b>Listing type:</b> {item.listing_type_id}</p><p><b>Item:</b> {p.meli_item_id ?? '—'}</p><p><b>Descripción:</b> {p.description_status}</p><p><b>Compatibilidad pendiente:</b> {p.local_payload?.compatibility_pending ? 'sí (sin escritura en Fase 7)' : 'no'}</p></div><div><h2 className="text-lg font-semibold">Controles</h2><div className="mt-2 flex flex-wrap gap-2"><button onClick={()=>post(p.id,'regenerar')} className="rounded border px-3 py-2 text-xs">Regenerar preflight</button><button disabled={!publisher.image_upload_enabled} onClick={()=>post(p.id,'imagenes')} className="rounded border px-3 py-2 text-xs disabled:opacity-40">Subir imágenes</button><button disabled={!publisher.remote_validation_enabled} onClick={()=>post(p.id,'validar')} className="rounded border px-3 py-2 text-xs disabled:opacity-40">Validar remotamente (no publica)</button><button onClick={()=>noteAction('revocar')} className="rounded border px-3 py-2 text-xs">Revocar</button><button disabled={!publisher.live_enabled} onClick={enqueue} className="rounded bg-rose-700 px-3 py-2 text-xs font-bold text-white disabled:opacity-40">Encolar publicación real</button><button onClick={()=>post(p.id,'descripcion/reintentar')} className="rounded border px-3 py-2 text-xs">Reintentar solo descripción</button><button onClick={reconcile} className="rounded border px-3 py-2 text-xs">Resolver reconciliación</button><button onClick={()=>noteAction('cancelar')} className="rounded border px-3 py-2 text-xs">Cancelar antes de publicar</button></div></div></section>
        <form onSubmit={approve} className="rounded-2xl border border-amber-300 p-5"><h2 className="font-semibold">Aprobación humana final (local, sin HTTP)</h2><div className="mt-3 grid gap-3 md:grid-cols-2"><textarea required value={approval.note} onChange={set('note')} placeholder="Nota obligatoria" className="rounded border p-2"/><input required value={approval.confirm_account_id} onChange={set('confirm_account_id')} placeholder={`Cuenta exacta: ${p.meli_account_id}`} className="rounded border p-2"/><input required value={approval.confirm_title} onChange={set('confirm_title')} placeholder="Escribe el título exacto" className="rounded border p-2"/><input required value={approval.confirm_price} onChange={set('confirm_price')} placeholder="Precio exacto" className="rounded border p-2"/><input required value={approval.confirm_stock} onChange={set('confirm_stock')} placeholder="Stock exacto" className="rounded border p-2"/><input required value={approval.confirm_category_id} onChange={set('confirm_category_id')} placeholder="Categoría exacta" className="rounded border p-2"/><input required minLength={8} maxLength={8} value={approval.confirm_fingerprint_suffix} onChange={set('confirm_fingerprint_suffix')} placeholder={`Últimos 8: ${p.request_fingerprint.slice(-8)}`} className="rounded border p-2"/><button className="rounded bg-amber-600 px-4 py-2 font-semibold text-white">Aprobar localmente</button></div></form>
        {p.error_message && <div className="rounded border border-rose-300 bg-rose-50 p-4"><b>{p.error_code}</b><p>{p.error_message}</p></div>}
        {['local_payload','validation_response','publication_response','picture_uploads','attempts','events'].map(key=><details key={key} className="rounded-xl border p-4"><summary className="cursor-pointer font-semibold">{key}</summary><pre className="mt-3 max-h-96 overflow-auto whitespace-pre-wrap text-xs">{JSON.stringify(p[key],null,2)}</pre></details>)}
    </div></AppShell>
}
