import AppShell from '@/Components/layout/AppShell'
import { Head, Link, useForm } from '@inertiajs/react'

export default function InventoryChannelLinkForm({ mode, link, products = [], channels = [] }) {
    const editing = mode === 'edit'
    const { data, setData, post, patch, processing, errors } = useForm({ inventory_product_id: link?.inventory_product_id || '', channel: link?.channel || '', account_key: link?.account_key || '', external_product_id: link?.external_product_id || '', external_variant_id: link?.external_variant_id || '', external_listing_id: link?.external_listing_id || '', external_url: link?.external_url || '', remote_status: link?.remote_status || '', remote_price: link?.remote_price || '', remote_currency: link?.remote_currency || '', is_active: link?.is_active ?? true })
    const submit = (event) => { event.preventDefault(); editing ? patch(`/almacen/canales/${link.id}`) : post('/almacen/canales') }
    const fieldError = (key) => errors[key] && <p className="mt-1 text-sm text-rose-600">{errors[key]}</p>
    return <AppShell title={editing ? 'Editar enlace' : 'Nuevo enlace'}><Head title={editing ? 'Editar enlace' : 'Nuevo enlace'} /><div className="mx-auto max-w-2xl space-y-6"><Link href="/almacen/canales" className="text-sm font-semibold text-indigo-600 hover:underline">← Volver</Link><h1 className="text-3xl font-bold text-slate-900 dark:text-white">{editing ? 'Editar enlace de canal' : 'Nuevo enlace de canal'}</h1><form onSubmit={submit} className="space-y-5 rounded-2xl border border-slate-200 bg-white p-6 dark:border-neutral-800 dark:bg-neutral-900"><label><span className="mb-1 block text-sm font-semibold">Producto *</span><select value={data.inventory_product_id} onChange={(e) => setData('inventory_product_id', e.target.value)} className="w-full rounded-xl border px-4 py-2.5 dark:border-neutral-700 dark:bg-neutral-950 dark:text-white"><option value="">Selecciona un producto</option>{products.map((product) => <option key={product.id} value={product.id}>{product.name} · {product.sku}</option>)}</select>{fieldError('inventory_product_id')}</label><label><span className="mb-1 block text-sm font-semibold">Canal *</span><select value={data.channel} onChange={(e) => setData('channel', e.target.value)} className="w-full rounded-xl border px-4 py-2.5 dark:border-neutral-700 dark:bg-neutral-950 dark:text-white"><option value="">Selecciona un canal</option>{channels.map((item) => <option key={item} value={item}>{item}</option>)}</select>{fieldError('channel')}</label>{[['account_key','Cuenta'],['external_listing_id','ID publicación'],['external_product_id','ID producto'],['external_variant_id','ID variante'],['external_url','URL externa'],['remote_status','Estado remoto'],['remote_currency','Moneda']].map(([key, label]) => <label key={key}><span className="mb-1 block text-sm font-semibold">{label}</span><input value={data[key]} onChange={(e) => setData(key, e.target.value)} className="w-full rounded-xl border px-4 py-2.5 dark:border-neutral-700 dark:bg-neutral-950 dark:text-white" />{fieldError(key)}</label>)}<label><span className="mb-1 block text-sm font-semibold">Precio remoto</span><input type="number" min="0" step="0.01" value={data.remote_price} onChange={(e) => setData('remote_price', e.target.value)} className="w-full rounded-xl border px-4 py-2.5 dark:border-neutral-700 dark:bg-neutral-950 dark:text-white" />{fieldError('remote_price')}</label><label className="flex items-center gap-3"><input type="checkbox" checked={Boolean(data.is_active)} onChange={(e) => setData('is_active', e.target.checked)} /><span className="text-sm font-semibold">Enlace activo</span></label><div className="flex justify-end gap-3"><Link href="/almacen/canales" className="rounded-xl border px-5 py-2.5 font-semibold">Cancelar</Link><button disabled={processing} className="rounded-xl bg-indigo-600 px-5 py-2.5 font-semibold text-white">Guardar</button></div></form></div></AppShell>
}
