import AppShell from '@/Components/layout/AppShell'
import { Head, Link, router, usePage } from '@inertiajs/react'

export default function InventoryChannelLinkShow({ link, canManage = false, lastSuccessfulStockSync = null }) {
    const { flash } = usePage().props
    const toggleStock = () => router.patch(`/almacen/canales/${link.id}/stock-sync`, { enabled: !link.stock_sync_enabled }, { preserveScroll: true })

    return <AppShell title="Detalle de enlace"><Head title="Detalle de enlace" /><div className="mx-auto max-w-2xl space-y-6"><Link href="/almacen/canales" className="text-sm font-semibold text-indigo-600 hover:underline">← Volver a enlaces</Link>{flash.success && <div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-semibold text-emerald-800">{flash.success}</div>}<div className="rounded-2xl border border-slate-200 bg-white p-6 dark:border-neutral-800 dark:bg-neutral-900"><div className="flex items-start justify-between gap-4"><div><h1 className="text-2xl font-bold dark:text-white">{link.product?.name}</h1><p className="font-mono text-sm text-slate-500">{link.product?.sku}</p></div>{canManage && <Link href={`/almacen/canales/${link.id}/editar`} className="rounded-xl bg-indigo-600 px-4 py-2 font-semibold text-white">Editar</Link>}</div><dl className="mt-6 grid gap-4 sm:grid-cols-2"><div><dt className="text-xs uppercase text-slate-500">Canal</dt><dd className="mt-1 dark:text-white">{link.channel}</dd></div><div><dt className="text-xs uppercase text-slate-500">Cuenta</dt><dd className="mt-1 dark:text-white">{link.account_key || '—'}</dd></div><div><dt className="text-xs uppercase text-slate-500">Producto externo</dt><dd className="mt-1 font-mono dark:text-white">{link.external_product_id || '—'}</dd></div><div><dt className="text-xs uppercase text-slate-500">Variante externa</dt><dd className="mt-1 font-mono dark:text-white">{link.external_variant_id || '—'}</dd></div><div><dt className="text-xs uppercase text-slate-500">Publicación externa</dt><dd className="mt-1 font-mono dark:text-white">{link.external_listing_id || '—'}</dd></div><div><dt className="text-xs uppercase text-slate-500">Vínculo activo</dt><dd className="mt-1 dark:text-white">{link.is_active ? 'Sí' : 'No'}</dd></div><div><dt className="text-xs uppercase text-slate-500">Sincronización de stock</dt><dd className="mt-1 dark:text-white">{link.stock_sync_enabled ? 'Activada' : 'Desactivada'}</dd></div><div><dt className="text-xs uppercase text-slate-500">Estado remoto</dt><dd className="mt-1 dark:text-white">{link.remote_status || 'sin estado remoto'}</dd></div><div className="sm:col-span-2"><dt className="text-xs uppercase text-slate-500">URL</dt><dd className="mt-1 break-all dark:text-white">{link.external_url || '—'}</dd></div></dl>{canManage && link.channel === 'mercado_libre' && <button type="button" onClick={toggleStock} className="mt-6 rounded-xl border px-4 py-2 text-sm font-semibold">{link.stock_sync_enabled ? 'Desactivar sincronización de stock' : 'Activar sincronización de stock'}</button>}{lastSuccessfulStockSync && <p className="mt-4 text-sm text-slate-500">Último target enviado correctamente: {lastSuccessfulStockSync.target_quantity}</p>}</div></div></AppShell>
}
